### ISSUE TITLE
Example with Python `range` + wrong variable

### ISSUE THREAD

**Issue by MFolschette** [potassco/guide#21]
These issues are both about line 10 in the following example file:
https://github.com/potassco/guide/blob/8af8ffc767b16cb12accceb622d753cbe1e34467/examples/rng-py.lp#L10

1) When tested with a fresh install from Conda (Python 3.6), the following error happens:

```
*** ERROR: (clingo): range.lp:15:9-18: error: error calling python function:
  RuntimeError: cannot convert to value: unexpected range() object
```

This is probably due to the fact that Python 3 returns a `range` object when using function `range` and not a `list`. Here is a fix:

```
  return list(range(na, na + 1))
```

However, maybe this works well with Python 2.

2) Moreover, the `return` above mentions `na` twice, which is most probably a typo (the Lua example mentions `na` and `nb`).

**Comment by rkaminsk** [comment]
Hi, I am going to address the first issue in clingo itself. There is no reason to restrict accepted return values to lists. Any sequence should be accepted. The second issue is a bug in the python example. Thanks, for reporting.

**Comment by rkaminsk** [comment]
I fixed the example and also clingo accepts sequences as return values now. See potassco/clingo#147.
