### ISSUE TITLE
Tower of Hanoi doesn't work in Online Runner

### ISSUE THREAD

**Issue by d4hines** [potassco/guide#23]
Hello,
I copied the following code from the guide:
```
% Generate
{ move(D,P,T) : disk(D), peg(P) } = 1 :- moves(M),
T = 1..M.
% Define
move(D,T) :- move(D,_,T).
on(D,P,0) :- init_on(D,P).
on(D,P,T) :- move(D,P,T).
on(D,P,T+1) :- on(D,P,T), not move(D,T+1),
not moves(T).
blocked(D-1,P,T+1) :- on(D,P,T), not moves(T).
blocked(D-1,P,T) :- blocked(D,P,T), disk(D).
% Test
:- move(D,P,T), blocked(D-1,P,T).
:- move(D,T), on(D,P,T-1), blocked(D,P,T).
:- goal_on(D,P), not on(D,P,M), moves(M).
:- { on(D,P,T) } != 1, disk(D), moves(M), T = 1..M.
% Display
#show move/3.
```

However, in the runner at https://potassco.org/clingo/run/, an answer isn't returned. Rather, it prints the following:
```
-:2:17-24: info: atom does not occur in any rule head:
  disk(D)

-:2:26-32: info: atom does not occur in any rule head:
  peg(P)

-:2:42-50: info: atom does not occur in any rule head:
  moves(M)

-:6:14-26: info: atom does not occur in any rule head:
  init_on(D,P)

-:9:5-13: info: atom does not occur in any rule head:
  moves(T)

-:10:38-46: info: atom does not occur in any rule head:
  moves(T)

-:11:37-44: info: atom does not occur in any rule head:
  disk(D)

-:15:4-16: info: atom does not occur in any rule head:
  goal_on(D,P)

-:15:33-41: info: atom does not occur in any rule head:
  moves(M)

-:16:24-31: info: atom does not occur in any rule head:
  disk(D)

-:16:33-41: info: atom does not occur in any rule head:
  moves(M)
```

Any guidance would be much appreciated!

**Comment by sefeoglu** [comment]
You should add these initials
`peg(a;b;c).
disk(1..4).
init_on(1..4,a).
goal_on(1..4,c).
moves(15).`

> Hello,
> I copied the following code from the guide:
> 
> ```
> % Generate
> { move(D,P,T) : disk(D), peg(P) } = 1 :- moves(M),
> T = 1..M.
> % Define
> move(D,T) :- move(D,_,T).
> on(D,P,0) :- init_on(D,P).
> on(D,P,T) :- move(D,P,T).
> on(D,P,T+1) :- on(D,P,T), not move(D,T+1),
> not moves(T).
> blocked(D-1,P,T+1) :- on(D,P,T), not moves(T).
> blocked(D-1,P,T) :- blocked(D,P,T), disk(D).
> % Test
> :- move(D,P,T), blocked(D-1,P,T).
> :- move(D,T), on(D,P,T-1), blocked(D,P,T).
> :- goal_on(D,P), not on(D,P,M), moves(M).
> :- { on(D,P,T) } != 1, disk(D), moves(M), T = 1..M.
> % Display
> #show move/3.
> ```
> 
> However, in the runner at https://potassco.org/clingo/run/, an answer isn't returned. Rather, it prints the following:
> 
> ```
> -:2:17-24: info: atom does not occur in any rule head:
>   disk(D)
> 
> -:2:26-32: info: atom does not occur in any rule head:
>   peg(P)
> 
> -:2:42-50: info: atom does not occur in any rule head:
>   moves(M)
> 
> -:6:14-26: info: atom does not occur in any rule head:
>   init_on(D,P)
> 
> -:9:5-13: info: atom does not occur in any rule head:
>   moves(T)
> 
> -:10:38-46: info: atom does not occur in any rule head:
>   moves(T)
> 
> -:11:37-44: info: atom does not occur in any rule head:
>   disk(D)
> 
> -:15:4-16: info: atom does not occur in any rule head:
>   goal_on(D,P)
> 
> -:15:33-41: info: atom does not occur in any rule head:
>   moves(M)
> 
> -:16:24-31: info: atom does not occur in any rule head:
>   disk(D)
> 
> -:16:33-41: info: atom does not occur in any rule head:
>   moves(M)
> ```
> 
> Any guidance would be much appreciated!

You should add these intials
`peg(a;b;c).
disk(1..4).
init_on(1..4,a).
goal_on(1..4,c).
moves(15).
% Generate
{ move(D,P,T) : disk(D), peg(P) } = 1 :- moves(M),
T = 1..M.`

**Comment by d4hines** [comment]
Oh, I see my mistake now. Thanks!
