### ISSUE TITLE
Small typos in documentation

### ISSUE THREAD

**Issue by damianoazzolini** [potassco/guide#26]
In the pdf documentation:

Section 11.2.3 pag 97: The input language of asprinextends (missing space between asprin and extends)
Section 11.2.5 pag 101: The preference library of asprinimplements (missing space between asprin and implements)
However, they are not crucial...

**Comment by tortinator** [comment]
Thank you, @damianoazzolini !

**Comment by javier-romero** [comment]
Thank you @damianoazzolini 
@tortinator: I fixed it in a pull request
