### ISSUE TITLE
Quickstart: Problem Solution

### ISSUE THREAD

**Issue by flip111** [potassco/guide#3]
In section 2.3 of the guide i see the answer of the towers of hanoi

```
clingo version 4.4.0
Reading from toh_ins.lp ...
Solving...
Answer: 1
move(4,b,1) move(3,c,2) move(4,c,3) move(2,b,4) \
move(4,a,5) move(3,b,6) move(4,b,7) move(1,c,8) \
move(4,c,9) move(3,a,10) move(4,a,11) move(2,c,12) \
move(4,b,13) move(3,c,14) move(4,c,15)
SATISFIABLE

Models: 1+
Calls: 1
Time: 0.017s (Solving: 0.01s 1st Model: 0.01s \
                                 Unsat: 0.00s)
CPU Time : 0.010s
```

Now i use the latest clingo version (5.2.2) and the output does not show the moves anymore. How do i get the answer with the new clingo version? Perhaps the guide can give some information on how to work with the newer clingo version. This is the output that i get:

```
clingo version 5.2.2
Reading from toh_ins.lp
Solving...
Answer: 1
disk(1) disk(2) disk(3) disk(4) init_on(1,a) init_on(2,a) init_on(3,a) init_on(4,a) goal_on(1,c) goal_on(2,c) goal_on(3,c) goal_on(4,c) moves(15) peg(a) peg(b) peg(c)
SATISFIABLE

Models       : 1
Calls        : 1
Time         : 0.001s (Solving: 0.00s 1st Model: 0.00s Unsat: 0.00s)
CPU Time     : 0.000s
```

**Comment by flip111** [comment]
Oops this question is silly, i see my mistake was forgetting the second file. It's a bit strange though that even if i specify the second file i still only see `Reading from toh_ins.lp ...` and not `toh_enc.lp` also.

**Comment by rkaminsk** [comment]
Clingo only prints the first file. If you look closely, you see the ellipsis in the first listing. We tried to keep the output short. If the first file name is long, it will also be shortened.
