### ISSUE TITLE
Inconsistency between guide and program

### ISSUE THREAD

**Issue by Gabbosaur** [potassco/guide#35]
While reading the guide, I've found an issue at page 39 on the booking hotel problem.
It says

> Thus, hotel 3 and 5 remain as optimal with respect to the second most significant optimization statement in Line 9.

But after computing the optimal answer set with
```
clingo opt.lp 0
```

it gives me this
```
clingo version 5.4.0
Reading from opt.lp
Solving...
Answer: 1
main_street(4) star(1,5) star(2,4) star(3,3) star(4,3) star(5,2) cost(1,170) cost(2,140) cost(3,90) cost(4,75) cost(5,60) hotel(1)
Optimization: 0 34 -5
Answer: 2
main_street(4) star(1,5) star(2,4) star(3,3) star(4,3) star(5,2) cost(1,170) cost(2,140) cost(3,90) cost(4,75) cost(5,60) hotel(3)
Optimization: 0 30 -3
OPTIMUM FOUND

Models       : 2
  Optimum    : yes
Optimization : 0 30 -3
Calls        : 1
Time         : 0.010s (Solving: 0.00s 1st Model: 0.00s Unsat: 0.00s)
CPU Time     : 0.000s
```

which it clearly says that it is choosing either hotel 1 or hotel 3, and not hotel 3 or hotel 5 as stated in the guide.
In the end it gives me the optimal solution but there is this discrepancy between the guide and the program.
Correct me if I am wrong, thanks!

**Comment by rkaminsk** [comment]
> which it clearly says that it is choosing either hotel 1 or hotel 3, and not hotel 3 or hotel 5 as stated in the guide.

The first answer is an intermediate model that is not optimal. Only the last reported answer is optimal. The solver can also be configured to enumerate all optimal solutions and hide intermediate ones. For this example there will be only one solution:
```
clingo opt.lp --opt-mode=optN -q1 0
clingo version 5.5.2 (a695cc4)
Reading from opt.lp
Solving...
Answer: 1
main_street(4) star(1,5) star(2,4) star(3,3) star(4,3) star(5,2) cost(1,170) cost(2,140) cost(3,90) cost(4,75) cost(5,60) hotel(3)
Optimization: 0 30 -3
OPTIMUM FOUND

Models       : 4
  Optimum    : yes
Optimization : 0 30 -3
Calls        : 1
Time         : 0.003s (Solving: 0.00s 1st Model: 0.00s Unsat: 0.00s)
CPU Time     : 0.003s
```
(If you comment out the rule maximizing the stars, there will be two answer sets.)

**Comment by Gabbosaur** [comment]
Oh okay, I think I understood, thank you. In that page there wasn't anything that cited the extra commands.
So `--opt-mode=optN` prints all the optimal answers as last answers while also printing some random answer in the first iterations.
`-q1` I guess it's an abbreviation for `--quiet=1` and prints only the optimal answers, am I right?

I have another question to ask. Is there any way to print optimal answers and sub-optimal answers?
Thanks.

**Comment by rkaminsk** [comment]
> Oh okay, I think I understood, thank you. In that page there wasn't anything that cited the extra commands. So `--opt-mode=optN` prints all the optimal answers as last answers while also printing some random answer in the first iterations. `-q1` I guess it's an abbreviation for `--quiet=1` and prints only the optimal answers, am I right?

:+1: 

> I have another question to ask. Is there any way to print optimal answers and sub-optimal answers? Thanks.

You might be interested in the following: <https://github.com/potassco/clingo/tree/master/examples/clingo/opt-enum>.

**Comment by Gabbosaur** [comment]
Thanks. I've tried to use `clingo myfile.lp --opt-mode=optN --restore` to display other solutions as stated in the link you've provided but it doesn't exist in clingo.
```
*** ERROR: (clingo): In context '<clingo>': unknown option: 'restore'
*** Info : (clingo): Try '--help' for usage information
```

I saw that you're launching lp files through python and not with clingo anymore which is kinda confusing.

**Comment by rkaminsk** [comment]
The example uses clingo's python module. The readme shows example calls at the bottom of the page.

**Comment by Gabbosaur** [comment]
I think I managed to make it work, now it prints all the answers from the optimal one to the least one. Thanks!
Will this feature be implemented into clingo in the future? Or is it going to be only available through python?

**Comment by rkaminsk** [comment]
For now it is only available via Python. Maybe this feature will be implemented in the future. Right now, no one is working on it.

**Comment by rkaminsk** [comment]
Closing this. If you have further questions just open another issue or use our mailing list.

- https://sourceforge.net/projects/potassco/lists/potassco-users
