### ISSUE TITLE
Does ASP support floating point numeric values?

### ISSUE THREAD

**Issue by Gabbosaur** [potassco/guide#36]
Hi, I was looking around the guide and didn't find anything about float values, hence only integers.
I tried if a division produces floats and the answer is no, it gives me an integer result.
If I try to declare a fact like
```
num('3.2').
div('2').
res(R) :- num(X), div(Y), R = X/Y.
```
or

```
num("3,2").
div("2").

res(R) :- num(X), div(Y), R = X/Y.
```
or any other combination of "" or ' ' or with dot or comma as float, clingo gives me errors.
So I assume that it supports only integers as numeric values. Correct me if I am wrong. Thanks!

**Comment by rkaminsk** [comment]
Clingo supports only integer values. There are some ways around this. You could define your own external functions to work with floating point numbers stored in strings or use one of the clingo extensions supporting constraints over floating point numbers.

## Extensions

- https://github.com/potassco/clingoLP
- https://github.com/potassco/clingo-dl
- https://github.com/potassco/clingo-lpx

## External Functions

```python
#script (python)

from clingo.symbol import String, SymbolType


def to_float(a):
    if a.type == SymbolType.Number:
        return float(a.number)
    if a.type == SymbolType.String:
        return float(a.string)
    raise TypeError('to_float: invalid symbol')


def divide(a, b):
    return String(str(to_float(a) / to_float(b)))

#end.

num("3.2").
div(2).
res(@divide(X,Y)) :- num(X), div(Y).
```

This will result in:
```
➜ clingo float.lp
clingo version 5.5.2 (4755e2e)
Reading from float.lp
Solving...
Answer: 1
div(2) num("3.2") res("1.6")
SATISFIABLE

Models       : 1
Calls        : 1
Time         : 0.131s (Solving: 0.00s 1st Model: 0.00s Unsat: 0.00s)
CPU Time     : 0.131s
```

**Comment by Gabbosaur** [comment]
Thanks, all clear!
