### ISSUE TITLE
Examples are under GPL

### ISSUE THREAD

**Issue by domoritz** [potassco/guide#4]
Since Potassco changed to MIT, are the examples also under MIT now? See https://github.com/potassco/guide/search?utf8=%E2%9C%93&q=general+public+license&type=

**Comment by rkaminsk** [comment]
Most of the examples are under [CC BY-SA](https://creativecommons.org/licenses/by-sa/4.0/) license, which is also used for guide. In fact, most of them can probably also be used under the fair-use terms depending on the jurisdiction you are in. I can ask my co-authors @mgebser and @tortinator if it is okay to remove the license header from the examples altogether.

**Comment by tortinator** [comment]
Dropping GPL for examples is fine with me

**Comment by mgebser** [comment]
It's fine with me to change the license and/or remove the license header.
